export const ADD_SNEAKER = "ADD_SNEAKER";
export const UPDATE_SNEAKER = "UPDATE_SNEAKER";
export const DELETE_SNEAKER = "DELETE_SNEAKER";
export const GET_SNEAKER = "GET_SNEAKER";
export const GET_SNEAKERS = "GET_SNEAKERS";
export const START_SNEAKERS_LOADING = "SNEAKERS_LOADING";
export const SNEAKERS_ERROR = "SNEAKERS_ERROR";
export const REMOVE_ERRORS = "REMOVE_ERRORS";
